### ISSUE TITLE
All text becomes squares/rectangles on 1.20.1

### ISSUE THREAD

**Issue by Cocomere** [KreloX/GalosphereTrimming#1]
If I try loading the game with this mod enabled, all text becomes squares/rectangles. I'm a hundred percent sure it's this mod, because disabling just that solves the issue.

There's a known issue with newer Fabric API versions and Optifine/Optifabric (though I don't use those), so there's a chance there's some wonky interactions happening with the Fabric API.

Galosphere Trimming is version 1.0.0, Fabric API is version 0.91.0 and the game version is 1.20.1. If it helps, I can share my mod list, though it's ~170 items (hence why I'm not just including it automatically). 

![image](https://github.com/KreloX/GalosphereTrimming/assets/65450169/284932a9-b4a2-4b4e-8790-42f479c23a8c)

**Comment by Poopooracoocoo** [comment]
Unable to reproduce with just Fabric API, Galosphere, and Galosphere Trimming on Fabric Loader. Also tested with Sodium and Indium. Are you able to share a modpack export and a log?

**Comment by Cocomere** [comment]
I re-added it to get a fresh log, because I wasn't positive which of the previous ones had it enabled. The second one is exactly the same except that I removed Galosphere Trimming.

https://api.paste.ee/p/B6f0m
https://api.paste.ee/p/1A6fq

I'm not positive how exactly to set up a modpack, but I tried to do so from MultiMC. I only included the mods and did one as a .zip and another as the Modrinth .mrpack. The files are too big to upload here, so I put them on my google drive. I'm aware that there's a LOT of mods in there, and god only knows what's causing conflicts. I do have three resource packs, but none of them were active when I first ran into this issue. I can share what those are if you'd think it would help, though.

https://drive.google.com/file/d/1nMCzM1BVk2OvIxG_aScRITPkMZQAOriC/view?usp=sharing
https://drive.google.com/file/d/1NQ-8rrZN4VnyvlxgGn0x3gP68P0CIIYv/view?usp=sharing

I do have three resource packs, but none of them were active when I first ran into this issue. I can share what those are if you'd think it helps, though?
Also, this was all on a fresh instance. I realized I didn't mention that before, sorry.

**Comment by Poopooracoocoo** [comment]
Took me a while to do a binary search to get a minimal set of mods to reproduce this. 

[latest.log](https://github.com/KreloX/GalosphereTrimming/files/13802757/latest.log)

<details>
<summary> Log </summary>

````
[15:27:56] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.3
[15:27:57] [main/WARN]: Warnings were found!
 - Mod 'Elytra Trims' (elytratrims) 1.4.4 recommends any version between 0.1.0-beta.4 (inclusive) and 0.2.0 (exclusive) of command-config, which is missing!
	 - You should install any version between 0.1.0-beta.4 (inclusive) and 0.2.0 (exclusive) of command-config for the optimal experience.
[15:27:57] [main/INFO]: Loading 65 mods:
	- clutter 1.20-0.5.5
	- elytratrims 1.4.4
	   \-- conditional-mixin 0.3.2
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- galosphere 1.20.1-1.4.1
	   |-- midnightlib 1.1.0
	   \-- mm 2.3
	- galospheretrimming 1.20.1-1.0.0-quilt
	- geckolib 4.3.1
	   \-- com_eliotlash_mclib_mclib 20
	- java 17
	- minecraft 1.20.1
[15:27:57] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/anon/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:27:58] [main/INFO]: Compatibility level set to JAVA_17
[15:28:01] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[15:28:14] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 404 milliseconds
[15:28:21] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:28:22] [Render thread/INFO]: Setting user: Anon
[15:28:24] [Render thread/INFO]: [Clutter] Finished initializing.
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:silver_bomb
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:glow_flare
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:spectre_flare
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:sparkle
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:spectre
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:specterpillar
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:spectator_vision
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:berserker
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:preserved
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:pink_salt_pillar
[15:28:24] [Render thread/ERROR]: No data fixer registered for galosphere:pink_salt_shard
[15:28:25] [Render thread/INFO]: Definitely not up to no good
[15:28:26] [Render thread/INFO]: Making elytras fancier!
[15:28:26] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[15:28:27] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[15:28:30] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (clutter, conditional-mixin, elytratrims, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, galosphere, galospheretrimming, geckolib, midnightlib, mm)
[15:28:31] [Worker-Main-5/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[15:28:31] [Worker-Main-2/WARN]: File galosphere:sounds/block/pink_salt_pillar/emerge2.ogg does not exist, cannot add it to event galosphere:entity.pink_salt_pillar.emerge
[15:28:31] [Worker-Main-2/WARN]: File galosphere:sounds/block/pink_salt_pillar/emerge3.ogg does not exist, cannot add it to event galosphere:entity.pink_salt_pillar.emerge
[15:28:31] [Render thread/INFO]: [STDOUT]: (MidnightLib) Player hats successfully loaded!
[15:28:32] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: duplicate key: silver
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalArgumentException: duplicate key: silver
	at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1189) ~[?:?]
	at java.util.Map.ofEntries(Map.java:1668) ~[?:?]
	at dev.kikugie.elytratrims.resource.ETResourceListener$TrimEntries.getMaterials(ETResourceListener.java:86) ~[elytratrims-1.4.4+1.20.jar:?]
	at dev.kikugie.elytratrims.resource.ETResourceListener.getTrims(ETResourceListener.java:48) ~[elytratrims-1.4.4+1.20.jar:?]
	at dev.kikugie.elytratrims.resource.ETAtlasHolder.getTrims(ETAtlasHolder.java:94) ~[elytratrims-1.4.4+1.20.jar:?]
	at dev.kikugie.elytratrims.resource.ETAtlasHolder.getSprites(ETAtlasHolder.java:82) ~[elytratrims-1.4.4+1.20.jar:?]
	at dev.kikugie.elytratrims.resource.ETAtlasHolder.lambda$load$0(ETAtlasHolder.java:66) ~[elytratrims-1.4.4+1.20.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[15:28:32] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (clutter, conditional-mixin, elytratrims, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, galosphere, galospheretrimming, geckolib, midnightlib, mm)
[15:28:32] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[15:28:32] [Worker-Main-3/WARN]: File galosphere:sounds/block/pink_salt_pillar/emerge2.ogg does not exist, cannot add it to event galosphere:entity.pink_salt_pillar.emerge
[15:28:32] [Worker-Main-3/WARN]: File galosphere:sounds/block/pink_salt_pillar/emerge3.ogg does not exist, cannot add it to event galosphere:entity.pink_salt_pillar.emerge
[15:28:37] [Worker-Main-6/WARN]: Exception loading blockstate definition: 'galosphere:blockstates/lichen_cordyceps.json' in resourcepack: 'fabric' for variant: 'alive=true,bulb=false': Overlapping definition with: alive=true,alive_stage=0,bulb=false
[15:28:37] [Worker-Main-2/WARN]: Exception loading blockstate definition: 'galosphere:blockstates/lichen_cordyceps.json' in resourcepack: 'fabric' for variant: 'alive=true,bulb=false': Overlapping definition with: alive=true,alive_stage=0,bulb=false
[15:28:47] [Render thread/INFO]: Stopping!
[15:28:47] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1138) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1113) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:266) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

````

</details>

Feels like wasted effort... I found someone who reported this in [KikuGie's Discord server](https://discord.com/invite/TBgNUCfryS): https://discord.com/channels/1135884510613995590/1135975307308966048/1190217558582906900
